## Imports

In [3]:
from IPython import display
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    HistGradientBoostingClassifier
)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

import sys
import os
import pandas as pd
import numpy as np


path = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if path not in sys.path:
    sys.path.append(path)
    
from database.database import engine, SessionLocal
from models.sensor_data import Base, SensorData
from services.sensor_service import carregar_dados_bd

## Carregando os dados do banco de dados

In [4]:


df = carregar_dados_bd()

print(df.shape)
df.head()

Carregando dados do Banco de Dados...
Dados carregados com sucesso!
(166796, 27)

,_sa_instance_state,temperature_f,z_rms_acceleration_g,x_peak_velocity_in_s,temperature_c,x_rms_acceleration_g,x_peak_velocity_mm_s,x_rms_velocity_in_s,z_kurtosis,z_high_freq_rms_accel_g,...,id,x_peak_acceleration_g,x_crest_factor,z_rms_velocity_in_s,z_peak_vel_comp_freq_hz,z_peak_velocity_in_s,rpm,z_rms_velocity_mm_s,x_peak_vel_comp_freq_hz,z_peak_velocity_mm_s
0,<sqlalchemy.orm.state.InstanceState object at ...,74.00,0.046,0.0875,23.33,0.066,2.224,0.0619,3.276,0.007,...,1426,0.033,3.918,0.0427,61.0,0.0605,0.0,1.086,61.0,1.536
1,<sqlalchemy.orm.state.InstanceState object at ...,73.91,0.046,0.0880,23.28,0.067,2.236,0.0622,3.447,0.007,...,1427,0.040,4.924,0.0431,61.0,0.0609,0.0,1.095,61.0,1.549
2,<sqlalchemy.orm.state.InstanceState object at ...,74.00,0.046,0.0880,23.33,0.067,2.236,0.0622,3.447,0.007,...,1428,0.040,4.924,0.0431,61.0,0.0609,0.0,1.095,61.0,1.549
3,<sqlalchemy.orm.state.InstanceState object at ...,74.00,0.046,0.0873,23.33,0.066,2.218,0.0617,7.921,0.007,...,1429,0.100,10.929,0.0431,61.0,0.0610,0.0,1.096,61.0,1.550
4,<sqlalchemy.orm.state.InstanceState object at ...,73.96,0.047,0.0870,23.31,0.066,2.210,0.0615,3.245,0.007,...,1430,0.049,5.949,0.0440,61.0,0.0623,0.0,1.119,61.0,1.583

Verificação das infos

In [5]:
print(df.shape)
print(df.head())
print(df.info())

(166796, 27)
                                  _sa_instance_state  temperature_f  \
0  <sqlalchemy.orm.state.InstanceState object at ...          74.00
1  <sqlalchemy.orm.state.InstanceState object at ...          73.91
2  <sqlalchemy.orm.state.InstanceState object at ...          74.00
3  <sqlalchemy.orm.state.InstanceState object at ...          74.00
4  <sqlalchemy.orm.state.InstanceState object at ...          73.96

   z_rms_acceleration_g  x_peak_velocity_in_s  temperature_c  \
0                 0.046                0.0875          23.33
1                 0.046                0.0880          23.28
2                 0.046                0.0880          23.33
3                 0.046                0.0873          23.33
4                 0.047                0.0870          23.31

   x_rms_acceleration_g  x_peak_velocity_mm_s  x_rms_velocity_in_s  \
0                 0.066                 2.224               0.0619
1                 0.067                 2.236               0.0622
2                 0.067                 2.236               0.0622
3                 0.066                 2.218               0.0617
4                 0.066                 2.210               0.0615

   z_kurtosis  z_high_freq_rms_accel_g  ...    id  x_peak_acceleration_g  \
0       3.276                    0.007  ...  1426                  0.033
1       3.447                    0.007  ...  1427                  0.040
2       3.447                    0.007  ...  1428                  0.040
3       7.921                    0.007  ...  1429                  0.100
4       3.245                    0.007  ...  1430                  0.049

   x_crest_factor  z_rms_velocity_in_s  z_peak_vel_comp_freq_hz  \
0           3.918               0.0427                     61.0
1           4.924               0.0431                     61.0
2           4.924               0.0431                     61.0
3          10.929               0.0431                     61.0
4           5.949               0.0440                     61.0

  z_peak_velocity_in_s  rpm  z_rms_velocity_mm_s  x_peak_vel_comp_freq_hz  \
0               0.0605  0.0                1.086                     61.0
1               0.0609  0.0                1.095                     61.0
2               0.0609  0.0                1.095                     61.0
3               0.0610  0.0                1.096                     61.0
4               0.0623  0.0                1.119                     61.0

   z_peak_velocity_mm_s
0                 1.536
1                 1.549
2                 1.549
3                 1.550
4                 1.583

[5 rows x 27 columns]
<class 'pandas.DataFrame'>
RangeIndex: 166796 entries, 0 to 166795
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   _sa_instance_state       166796 non-null  object
 1   temperature_f            166796 non-null  float64
 2   z_rms_acceleration_g     166796 non-null  float64
 3   x_peak_velocity_in_s     166796 non-null  float64
 4   temperature_c            166796 non-null  float64
 5   x_rms_acceleration_g     166796 non-null  float64
 6   x_peak_velocity_mm_s     166796 non-null  float64
 7   x_rms_velocity_in_s      166796 non-null  float64
 8   z_kurtosis               166796 non-null  float64
 9   z_high_freq_rms_accel_g  166796 non-null  float64
 10  x_rms_velocity_mm_s      166796 non-null  float64
 11  x_kurtosis               166796 non-null  float64
 12  x_high_freq_rms_accel_g  166796 non-null  float64
 13  z_peak_acceleration_g    166796 non-null  float64
 14  z_crest_factor           166796 non-null  float64
 15  fault                    166796 non-null  str
 16  created_at               166796 non-null  datetime64[us]
 17  id                       166796 non-null  int64
 18  x_peak_acceleration_g    166796 non-null  float64
 19  x_crest_factor           166796 non-null  float64
 20  z_rms_velocity_in_s      166796 non-null  float64
 21  z_peak_vel_comp_freq_hz  166796 non-null  float64
 22  z_peak_velocity_in_s     166796 non-null  float64
 23  rpm                      166796 non-null  float64
 24  z_rms_velocity_mm_s      166796 non-null  float64
 25  x_peak_vel_comp_freq_hz  166796 non-null  float64
 26  z_peak_velocity_mm_s     166796 non-null  float64
dtypes: datetime64[us](1), float64(23), int64(1), object(1), str(1)
memory usage: 36.6+ MB
None

verificando os nulos

In [6]:
df.isnull().sum()

_sa_instance_state         0
temperature_f              0
z_rms_acceleration_g       0
x_peak_velocity_in_s       0
temperature_c              0
x_rms_acceleration_g       0
x_peak_velocity_mm_s       0
x_rms_velocity_in_s        0
z_kurtosis                 0
z_high_freq_rms_accel_g    0
x_rms_velocity_mm_s        0
x_kurtosis                 0
x_high_freq_rms_accel_g    0
z_peak_acceleration_g      0
z_crest_factor             0
fault                      0
created_at                 0
id                         0
x_peak_acceleration_g      0
x_crest_factor             0
z_rms_velocity_in_s        0
z_peak_vel_comp_freq_hz    0
z_peak_velocity_in_s       0
rpm                        0
z_rms_velocity_mm_s        0
x_peak_vel_comp_freq_hz    0
z_peak_velocity_mm_s       0
dtype: int64

Distribuição das falhas

In [7]:
df["fault"].value_counts()
print(df["fault"].value_counts(normalize=True))

fault
rolamento_inner            0.077940
eccentric_rotor            0.070793
desbalanceado_1parafuso    0.060427
cocked_rotor               0.059953
rolamento_outer            0.059953
                             ...
dedesbalanceado_adxl_1     0.000126
normal_6                   0.000120
acelerando                 0.000042
new_tes                    0.000012
new_teste                  0.000012
Name: proportion, Length: 151, dtype: float64

Removendo colunas que não auxiliam

In [8]:
df = df.drop(columns=[
    "_sa_instance_state",
    "id",
    "created_at"
])

Vou diminuir a amostra para treino (pc mais fraco)

In [9]:
df_amostra = df.sample(frac=0.8, random_state=42)

# Amostragem para evitar travamentos (só trocar na var acima a porcentagem, deixei 80%)
df = df_amostra
print(df.shape)

(133437, 24)

Setando X e Y

In [10]:
X = df.drop("fault", axis=1)

y = df["fault"]

In [11]:
# Tratando pouca amostra e nome sujo
min_amostras = 30
contagem = df["fault"].value_counts()
classes_boas = contagem[contagem >= min_amostras].index
df = df[df["fault"].isin(classes_boas)]
print("classes depois do filtro:", df["fault"].nunique())
print(df.shape)

classes depois do filtro: 145
(133368, 24)

separar features e target

In [12]:
X = df.drop("fault", axis=1)
y = df["fault"]
print(X.shape)
print(y.shape)

(133368, 23)
(133368,)

Separando o teste e treino

In [13]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
#Func para avaliar modelos
def avaliar(modelo, nome):

            print(f"Treinando {nome}...")

            modelo.fit(X_train, y_train)

            pred = modelo.predict(X_test)

            print(classification_report(y_test, pred))

            resultado = {
                "Modelo": nome,
                "Accuracy": accuracy_score(y_test, pred),
                "Precision": precision_score(y_test, pred, average="weighted"),
                "Recall": recall_score(y_test, pred, average="weighted"),
                "F1": f1_score(y_test, pred, average="weighted")
            }

            print(resultado)

            return resultado

Para guardar os resultados

In [15]:
resultados = []

Random forest

In [16]:
modelo = RandomForestClassifier(
            n_estimators=50,
            max_depth=10,
            random_state=42,
            n_jobs=2
        ) #limitei aqui por conta do pc usado nos testes

resultados.append(
    avaliar(modelo, "Random Forest")
)

Treinando Random Forest...
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       1.00      0.50      0.67        16
           2       0.47      0.60      0.53      1602
           3       0.78      0.52      0.62       483
           4       0.95      0.79      0.86        24
           5       1.00      0.62      0.77        24
           6       0.65      0.54      0.59        24
           7       0.64      0.90      0.75      1433
           8       0.72      0.55      0.63       472
           9       0.75      0.75      0.75         8
          10       1.00      0.25      0.40         8
          11       0.46      0.88      0.61       644
          12       0.55      0.50      0.52       633
          13       0.00      0.00      0.00        24
          14       0.75      0.72      0.73      1611
          15       0.88      0.19      0.31        37
          16       0.80      0.50      0.62        24
          17       1.00      0.20      0.33        15
          18       0.92      0.75      0.83        16
          19       0.00      0.00      0.00         7
          20       1.00      0.62      0.77        24
          21       0.87      0.57      0.68        23
          22       1.00      0.87      0.93        15
          23       1.00      0.69      0.81        16
          24       1.00      0.57      0.72        23
          25       0.88      0.64      0.74        22
          26       1.00      0.20      0.33        15
          27       1.00      1.00      1.00         8
          28       1.00      1.00      1.00         7
          29       1.00      0.48      0.65        25
          30       0.48      0.67      0.56      1881
          31       0.73      0.41      0.53       477
          32       0.86      0.72      0.78        25
          33       1.00      0.30      0.47        23
          34       0.70      0.28      0.40        25
          35       1.00      0.38      0.55        24
          36       1.00      0.18      0.31        22
          37       0.95      0.80      0.87        25
          38       1.00      1.00      1.00         9
          39       1.00      1.00      1.00        64
          40       0.67      1.00      0.80         8
          41       1.00      1.00      1.00        11
          42       0.91      0.42      0.57        24
          43       1.00      0.32      0.48        25
          44       1.00      0.50      0.67        24
          45       0.94      0.71      0.81        24
          46       1.00      0.75      0.86         8
          47       0.80      0.25      0.38        32
          48       0.64      0.29      0.40        31
          49       0.62      0.59      0.60        66
          50       0.94      0.52      0.67        33
          51       1.00      0.80      0.89        30
          52       0.79      0.97      0.87        32
          53       1.00      0.73      0.84        33
          54       1.00      0.84      0.92        32
          55       1.00      0.33      0.50        24
          56       1.00      0.25      0.40        24
          57       0.92      0.44      0.59        25
          58       1.00      0.31      0.47        26
          59       1.00      0.33      0.50        24
          60       0.86      0.25      0.39        24
          61       1.00      0.36      0.53        25
          62       1.00      0.46      0.63        24
          63       0.85      0.52      0.64        33
          64       0.67      0.32      0.43        31
          65       0.25      0.03      0.06        30
          66       0.66      0.59      0.62        32
          67       0.93      0.41      0.57        32
          68       1.00      0.21      0.34        34
          69       0.89      0.25      0.39        32
          70       0.94      0.44      0.60        34
          71       0.86      0.25      0.39        24
          72       0.00      0.00      0.00        24
          73       1.00      0.64      0.78        33
          74       1.00      0.67      0.80        33
          75       0.94      0.97      0.95        32
          76       1.00      0.47      0.64        32
          77       0.61      0.67      0.64        33
          78       1.00      0.53      0.69        32
          79       0.86      0.19      0.32        31
          80       0.93      0.41      0.57        32
          81       0.68      0.50      0.58        30
          82       0.75      0.39      0.51        31
          83       0.94      0.47      0.62        32
          84       1.00      0.55      0.71        33
          85       0.62      0.45      0.53        33
          86       0.92      0.39      0.55        31
          87       1.00      0.58      0.73        33
          88       0.90      0.31      0.46        29
          89       0.86      0.39      0.53        31
          90       0.90      0.64      0.75       919
          91       0.65      0.38      0.48       965
          92       0.41      0.46      0.43        24
          93       0.00      0.00      0.00        15
          94       0.85      0.74      0.79        23
          95       1.00      0.33      0.50        24
          96       0.89      0.32      0.47        25
          97       0.84      0.35      0.49        46
          98       0.90      0.38      0.53        24
          99       0.86      0.24      0.38        25
         100       0.00      0.00      0.00        16
         101       0.74      0.52      0.61        48
         102       0.91      0.62      0.74        16
         103       0.92      0.48      0.63        25
         104       0.86      0.75      0.80         8
         105       0.80      0.68      0.74      1433
         106       0.85      0.54      0.66       483
         107       0.38      0.39      0.38      1447
         108       0.82      0.68      0.74       482
         109       0.86      0.24      0.38        25
         110       1.00      0.04      0.08        24
         111       0.91      0.83      0.87        24
         112       0.96      0.96      0.96        25
         113       0.91      0.91      0.91        23
         114       0.96      1.00      0.98        24
         115       0.89      0.35      0.50        23
         116       0.72      0.67      0.70      1609
         117       0.71      0.88      0.79       485
         118       1.00      0.33      0.50        24
         119       1.00      0.36      0.53        25
         120       0.96      0.96      0.96        23
         121       1.00      1.00      1.00        24
         122       0.55      0.80      0.65      2082
         123       0.76      0.91      0.83       480
         124       0.00      0.00      0.00        23
         125       0.00      0.00      0.00        24
         126       0.94      0.68      0.79        25
         127       0.93      1.00      0.96        26
         128       1.00      0.73      0.84        22
         129       0.96      1.00      0.98        25
         130       0.59      0.64      0.61      1617
         131       0.99      0.35      0.51       481
         132       0.00      0.00      0.00        24
         133       1.00      0.48      0.65        25
         134       0.95      0.75      0.84        24
         135       1.00      0.25      0.40         8
         136       1.00      0.52      0.69        23
         137       1.00      0.77      0.87        22
         138       1.00      1.00      1.00         7
         139       1.00      0.87      0.93        23
         140       1.00      0.19      0.32        16
         141       0.69      0.73      0.71      1441
         142       0.88      0.51      0.65       481
         143       1.00      0.35      0.52        23
         144       0.75      0.25      0.38        24

    accuracy                           0.64     26674
   macro avg       0.82      0.52      0.60     26674
weighted avg       0.67      0.64      0.63     26674

{'Modelo': 'Random Forest', 'Accuracy': 0.6354502511809252, 'Precision': 0.6707360814427638, 'Recall': 0.6354502511809252, 'F1': 0.6298454298123792}

d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Extra trees

In [17]:
modelo = ExtraTreesClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=2
)

resultados.append(
    avaliar(modelo, "Extra Trees")
)

Treinando Extra Trees...
              precision    recall  f1-score   support

           0       1.00      0.88      0.93         8
           1       0.93      0.88      0.90        16
           2       0.78      0.80      0.79      1602
           3       0.82      0.86      0.84       483
           4       0.96      0.96      0.96        24
           5       1.00      0.92      0.96        24
           6       0.95      0.88      0.91        24
           7       0.89      0.96      0.92      1433
           8       0.87      0.79      0.83       472
           9       0.89      1.00      0.94         8
          10       1.00      0.62      0.77         8
          11       0.77      0.88      0.82       644
          12       0.76      0.81      0.78       633
          13       1.00      0.25      0.40        24
          14       0.85      0.88      0.87      1611
          15       0.81      0.70      0.75        37
          16       0.92      0.92      0.92        24
          17       0.93      0.87      0.90        15
          18       1.00      0.81      0.90        16
          19       1.00      0.43      0.60         7
          20       0.96      1.00      0.98        24
          21       0.87      0.87      0.87        23
          22       0.94      1.00      0.97        15
          23       0.94      0.94      0.94        16
          24       1.00      1.00      1.00        23
          25       0.88      1.00      0.94        22
          26       0.81      0.87      0.84        15
          27       1.00      1.00      1.00         8
          28       1.00      1.00      1.00         7
          29       0.89      1.00      0.94        25
          30       0.80      0.83      0.82      1881
          31       0.85      0.77      0.80       477
          32       0.96      0.92      0.94        25
          33       1.00      0.78      0.88        23
          34       0.77      0.68      0.72        25
          35       0.95      0.83      0.89        24
          36       0.90      0.82      0.86        22
          37       0.96      0.96      0.96        25
          38       1.00      1.00      1.00         9
          39       0.98      1.00      0.99        64
          40       1.00      1.00      1.00         8
          41       1.00      1.00      1.00        11
          42       0.95      0.79      0.86        24
          43       1.00      1.00      1.00        25
          44       0.91      0.88      0.89        24
          45       0.86      1.00      0.92        24
          46       1.00      0.75      0.86         8
          47       0.89      0.75      0.81        32
          48       0.93      0.90      0.92        31
          49       0.87      0.89      0.88        66
          50       0.89      0.97      0.93        33
          51       0.97      0.97      0.97        30
          52       0.94      1.00      0.97        32
          53       1.00      0.88      0.94        33
          54       0.97      1.00      0.98        32
          55       0.83      0.83      0.83        24
          56       0.88      0.88      0.88        24
          57       0.92      0.88      0.90        25
          58       0.86      0.96      0.91        26
          59       0.77      0.71      0.74        24
          60       0.91      0.88      0.89        24
          61       0.88      0.88      0.88        25
          62       0.95      0.79      0.86        24
          63       0.96      0.79      0.87        33
          64       0.83      0.65      0.73        31
          65       0.73      0.73      0.73        30
          66       0.85      0.88      0.86        32
          67       0.90      0.84      0.87        32
          68       0.94      0.88      0.91        34
          69       0.97      0.91      0.94        32
          70       0.94      0.91      0.93        34
          71       0.96      0.96      0.96        24
          72       0.91      0.88      0.89        24
          73       1.00      1.00      1.00        33
          74       0.97      0.94      0.95        33
          75       1.00      1.00      1.00        32
          76       0.97      0.97      0.97        32
          77       0.97      0.94      0.95        33
          78       1.00      0.88      0.93        32
          79       0.97      0.90      0.93        31
          80       1.00      0.94      0.97        32
          81       0.84      0.90      0.87        30
          82       1.00      0.97      0.98        31
          83       0.94      0.97      0.95        32
          84       1.00      1.00      1.00        33
          85       0.94      0.97      0.96        33
          86       0.91      1.00      0.95        31
          87       0.94      0.94      0.94        33
          88       0.93      0.97      0.95        29
          89       0.93      0.81      0.86        31
          90       0.93      0.83      0.87       919
          91       0.77      0.74      0.75       965
          92       0.95      0.88      0.91        24
          93       0.82      0.60      0.69        15
          94       0.92      0.96      0.94        23
          95       1.00      1.00      1.00        24
          96       0.92      0.92      0.92        25
          97       0.91      0.85      0.88        46
          98       1.00      0.96      0.98        24
          99       0.96      0.88      0.92        25
         100       0.94      1.00      0.97        16
         101       1.00      1.00      1.00        48
         102       1.00      1.00      1.00        16
         103       0.96      1.00      0.98        25
         104       1.00      1.00      1.00         8
         105       0.88      0.86      0.87      1433
         106       0.86      0.82      0.84       483
         107       0.82      0.81      0.81      1447
         108       0.87      0.88      0.87       482
         109       0.88      0.88      0.88        25
         110       1.00      0.38      0.55        24
         111       1.00      0.96      0.98        24
         112       1.00      1.00      1.00        25
         113       0.96      1.00      0.98        23
         114       1.00      1.00      1.00        24
         115       0.91      0.87      0.89        23
         116       0.87      0.85      0.86      1609
         117       0.93      0.95      0.94       485
         118       0.88      0.58      0.70        24
         119       1.00      0.64      0.78        25
         120       1.00      1.00      1.00        23
         121       1.00      1.00      1.00        24
         122       0.87      0.91      0.89      2082
         123       0.90      0.96      0.93       480
         124       1.00      0.57      0.72        23
         125       1.00      0.29      0.45        24
         126       0.92      0.92      0.92        25
         127       0.93      1.00      0.96        26
         128       1.00      0.95      0.98        22
         129       1.00      1.00      1.00        25
         130       0.83      0.86      0.84      1617
         131       0.80      0.68      0.73       481
         132       0.76      0.54      0.63        24
         133       0.94      0.68      0.79        25
         134       1.00      1.00      1.00        24
         135       1.00      1.00      1.00         8
         136       1.00      0.83      0.90        23
         137       1.00      0.95      0.98        22
         138       1.00      1.00      1.00         7
         139       1.00      1.00      1.00        23
         140       1.00      0.94      0.97        16
         141       0.85      0.84      0.84      1441
         142       0.85      0.83      0.84       481
         143       1.00      0.48      0.65        23
         144       0.86      1.00      0.92        24

    accuracy                           0.85     26674
   macro avg       0.93      0.87      0.89     26674
weighted avg       0.85      0.85      0.85     26674

{'Modelo': 'Extra Trees', 'Accuracy': 0.8523281097698133, 'Precision': 0.8536039292163924, 'Recall': 0.8523281097698133, 'F1': 0.8514191352995294}

HGB

In [18]:
from sklearn.ensemble import HistGradientBoostingClassifier

modelo = HistGradientBoostingClassifier(max_iter=50, max_depth=10, 
    random_state=42
)

resultados.append(
    avaliar(modelo, "HistGradientBoosting")
)

Treinando HistGradientBoosting...
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.24      0.56      0.34        16
           2       0.61      0.56      0.59      1602
           3       0.74      0.62      0.68       483
           4       0.00      0.00      0.00        24
           5       0.02      0.04      0.02        24
           6       0.03      0.12      0.04        24
           7       0.80      0.77      0.78      1433
           8       0.58      0.46      0.51       472
           9       0.00      0.00      0.00         8
          10       0.10      0.38      0.15         8
          11       0.63      0.63      0.63       644
          12       0.62      0.57      0.59       633
          13       0.04      0.08      0.06        24
          14       0.65      0.47      0.54      1611
          15       0.25      0.43      0.32        37
          16       0.10      0.42      0.17        24
          17       0.03      0.13      0.05        15
          18       0.00      0.00      0.00        16
          19       0.00      0.00      0.00         7
          20       0.31      0.21      0.25        24
          21       0.15      0.17      0.16        23
          22       0.17      0.67      0.27        15
          23       0.07      0.06      0.06        16
          24       0.09      0.13      0.11        23
          25       0.14      0.32      0.20        22
          26       0.00      0.00      0.00        15
          27       0.20      0.25      0.22         8
          28       0.04      0.14      0.07         7
          29       0.02      0.08      0.03        25
          30       0.64      0.58      0.61      1881
          31       0.66      0.57      0.61       477
          32       0.32      0.44      0.37        25
          33       0.03      0.04      0.03        23
          34       0.20      0.68      0.31        25
          35       0.09      0.17      0.12        24
          36       0.12      0.18      0.14        22
          37       0.22      0.60      0.32        25
          38       0.00      0.00      0.00         9
          39       0.18      0.83      0.29        64
          40       0.00      0.00      0.00         8
          41       0.00      0.00      0.00        11
          42       0.06      0.17      0.09        24
          43       0.11      0.12      0.12        25
          44       0.00      0.00      0.00        24
          45       0.09      0.33      0.14        24
          46       0.00      0.00      0.00         8
          47       0.33      0.22      0.26        32
          48       0.06      0.10      0.07        31
          49       0.13      0.24      0.17        66
          50       0.05      0.09      0.06        33
          51       0.06      0.30      0.11        30
          52       0.16      0.22      0.19        32
          53       0.21      0.30      0.25        33
          54       0.03      0.12      0.04        32
          55       0.03      0.12      0.04        24
          56       0.08      0.08      0.08        24
          57       0.11      0.36      0.17        25
          58       0.12      0.23      0.16        26
          59       0.05      0.12      0.07        24
          60       0.32      0.29      0.30        24
          61       0.02      0.04      0.02        25
          62       0.21      0.50      0.30        24
          63       0.26      0.36      0.30        33
          64       0.11      0.23      0.15        31
          65       0.04      0.03      0.04        30
          66       0.13      0.62      0.21        32
          67       0.17      0.09      0.12        32
          68       0.21      0.32      0.26        34
          69       0.00      0.00      0.00        32
          70       0.03      0.12      0.05        34
          71       0.00      0.00      0.00        24
          72       0.13      0.08      0.10        24
          73       0.28      0.30      0.29        33
          74       0.01      0.03      0.02        33
          75       0.05      0.03      0.04        32
          76       0.00      0.00      0.00        32
          77       0.02      0.03      0.02        33
          78       0.10      0.19      0.13        32
          79       0.07      0.13      0.09        31
          80       0.00      0.00      0.00        32
          81       0.00      0.00      0.00        30
          82       0.10      0.26      0.15        31
          83       0.18      0.25      0.21        32
          84       0.07      0.24      0.11        33
          85       0.00      0.00      0.00        33
          86       0.04      0.13      0.06        31
          87       0.13      0.24      0.17        33
          88       0.04      0.14      0.06        29
          89       0.00      0.00      0.00        31
          90       0.68      0.27      0.38       919
          91       0.58      0.44      0.50       965
          92       0.22      0.42      0.29        24
          93       0.02      0.20      0.04        15
          94       0.60      0.52      0.56        23
          95       0.15      0.50      0.23        24
          96       0.10      0.16      0.12        25
          97       0.08      0.20      0.11        46
          98       0.07      0.12      0.09        24
          99       0.10      0.20      0.14        25
         100       0.05      0.25      0.09        16
         101       0.17      0.40      0.24        48
         102       0.23      0.62      0.34        16
         103       0.05      0.20      0.07        25
         104       0.00      0.00      0.00         8
         105       0.71      0.67      0.69      1433
         106       0.75      0.52      0.61       483
         107       0.52      0.46      0.49      1447
         108       0.70      0.48      0.57       482
         109       0.05      0.24      0.08        25
         110       0.07      0.17      0.10        24
         111       0.18      0.29      0.23        24
         112       0.05      0.04      0.05        25
         113       0.00      0.00      0.00        23
         114       0.00      0.00      0.00        24
         115       0.11      0.17      0.14        23
         116       0.73      0.35      0.47      1609
         117       0.80      0.73      0.77       485
         118       0.03      0.12      0.05        24
         119       0.05      0.20      0.09        25
         120       0.42      0.22      0.29        23
         121       0.00      0.00      0.00        24
         122       0.69      0.61      0.65      2082
         123       0.43      0.63      0.51       480
         124       0.00      0.00      0.00        23
         125       0.05      0.21      0.08        24
         126       0.06      0.24      0.10        25
         127       0.00      0.00      0.00        26
         128       0.00      0.00      0.00        22
         129       0.05      0.12      0.07        25
         130       0.66      0.57      0.61      1617
         131       0.49      0.30      0.38       481
         132       0.04      0.12      0.06        24
         133       0.05      0.12      0.07        25
         134       0.10      0.50      0.16        24
         135       0.00      0.00      0.00         8
         136       0.06      0.13      0.08        23
         137       0.31      0.41      0.35        22
         138       0.00      0.00      0.00         7
         139       0.01      0.04      0.02        23
         140       0.05      0.12      0.07        16
         141       0.74      0.56      0.64      1441
         142       0.66      0.43      0.52       481
         143       0.03      0.13      0.04        23
         144       0.11      0.17      0.13        24

    accuracy                           0.50     26674
   macro avg       0.18      0.24      0.19     26674
weighted avg       0.60      0.50      0.53     26674

{'Modelo': 'HistGradientBoosting', 'Accuracy': 0.5010872010197196, 'Precision': 0.5989268397150616, 'Recall': 0.5010872010197196, 'F1': 0.5348763969480977}

d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

XGBoost

In [ ]:
from xgboost import XGBClassifier

modelo = XGBClassifier(n_estimators=50, max_depth=40,
    random_state=42,
    eval_metric="mlogloss",
    tree_method="hist"
)

resultados.append(
    avaliar(modelo, "XGBoost")
)

Treinando XGBoost...
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.94      0.97        16
           2       0.79      0.79      0.79      1602
           3       0.80      0.83      0.82       483
           4       0.89      1.00      0.94        24
           5       0.95      0.88      0.91        24
           6       0.88      0.88      0.88        24
           7       0.92      0.96      0.94      1433
           8       0.85      0.81      0.83       472
           9       1.00      0.88      0.93         8
          10       1.00      0.62      0.77         8
          11       0.78      0.83      0.80       644
          12       0.72      0.74      0.73       633
          13       0.70      0.29      0.41        24
          14       0.86      0.88      0.87      1611
          15       0.67      0.76      0.71        37
          16       0.77      0.83      0.80        24
          17       0.92      0.73      0.81        15
          18       0.88      0.94      0.91        16
          19       1.00      0.71      0.83         7
          20       0.96      1.00      0.98        24
          21       0.92      0.96      0.94        23
          22       0.94      1.00      0.97        15
          23       1.00      0.94      0.97        16
          24       0.96      1.00      0.98        23
          25       0.88      0.95      0.91        22
          26       0.82      0.93      0.88        15
          27       1.00      1.00      1.00         8
          28       0.78      1.00      0.88         7
          29       0.96      1.00      0.98        25
          30       0.82      0.83      0.82      1881
          31       0.80      0.79      0.79       477
          32       0.89      0.96      0.92        25
          33       1.00      0.74      0.85        23
          34       0.77      0.68      0.72        25
          35       1.00      0.96      0.98        24
          36       1.00      0.82      0.90        22
          37       0.89      1.00      0.94        25
          38       1.00      1.00      1.00         9
          39       1.00      1.00      1.00        64
          40       0.67      1.00      0.80         8
          41       1.00      1.00      1.00        11
          42       0.79      0.79      0.79        24
          43       0.92      0.96      0.94        25
          44       0.92      0.92      0.92        24
          45       1.00      0.92      0.96        24
          46       1.00      0.88      0.93         8
          47       0.80      0.88      0.84        32
          48       0.93      0.90      0.92        31
          49       0.89      0.83      0.86        66
          50       0.92      1.00      0.96        33
          51       0.94      0.97      0.95        30
          52       0.94      1.00      0.97        32
          53       1.00      0.94      0.97        33
          54       1.00      1.00      1.00        32
          55       0.95      0.88      0.91        24
          56       0.95      0.83      0.89        24
          57       0.96      0.92      0.94        25
          58       0.93      1.00      0.96        26
          59       0.87      0.83      0.85        24
          60       0.88      0.92      0.90        24
          61       0.95      0.80      0.87        25
          62       0.92      0.92      0.92        24
          63       0.89      0.97      0.93        33
          64       0.88      0.74      0.81        31
          65       0.65      0.73      0.69        30
          66       0.92      0.72      0.81        32
          67       0.96      0.81      0.88        32
          68       0.97      0.94      0.96        34
          69       0.97      0.91      0.94        32
          70       0.97      0.91      0.94        34
          71       0.87      0.83      0.85        24
          72       0.89      0.67      0.76        24
          73       0.97      0.91      0.94        33
          74       1.00      0.91      0.95        33
          75       0.94      1.00      0.97        32
          76       0.94      0.97      0.95        32
          77       1.00      0.97      0.98        33
          78       0.97      0.91      0.94        32
          79       1.00      0.84      0.91        31
          80       0.93      0.84      0.89        32
          81       0.85      0.93      0.89        30
          82       1.00      0.90      0.95        31
          83       0.94      0.91      0.92        32
          84       0.97      0.94      0.95        33
          85       0.97      0.94      0.95        33
          86       0.82      0.90      0.86        31
          87       0.97      1.00      0.99        33
          88       0.83      0.86      0.85        29
          89       0.88      0.74      0.81        31
          90       0.93      0.89      0.91       919
          91       0.75      0.73      0.74       965
          92       0.91      0.83      0.87        24
          93       0.62      0.67      0.65        15
          94       1.00      0.87      0.93        23
          95       0.96      0.96      0.96        24
          96       1.00      0.84      0.91        25
          97       0.88      0.91      0.89        46
          98       0.92      1.00      0.96        24
          99       0.92      0.92      0.92        25
         100       1.00      1.00      1.00        16
         101       1.00      0.98      0.99        48
         102       1.00      0.94      0.97        16
         103       1.00      0.92      0.96        25
         104       1.00      1.00      1.00         8
         105       0.88      0.86      0.87      1433
         106       0.87      0.84      0.85       483
         107       0.81      0.80      0.81      1447
         108       0.87      0.89      0.88       482
         109       0.92      0.96      0.94        25
         110       0.76      0.54      0.63        24
         111       0.92      1.00      0.96        24
         112       0.96      1.00      0.98        25
         113       1.00      1.00      1.00        23
         114       1.00      0.96      0.98        24
         115       0.95      0.87      0.91        23
         116       0.86      0.85      0.85      1609
         117       0.94      0.97      0.96       485
         118       0.80      0.67      0.73        24
         119       0.85      0.68      0.76        25
         120       1.00      1.00      1.00        23
         121       1.00      1.00      1.00        24
         122       0.89      0.89      0.89      2082
         123       0.94      0.94      0.94       480
         124       0.93      0.57      0.70        23
         125       0.83      0.42      0.56        24
         126       0.93      1.00      0.96        25
         127       1.00      0.88      0.94        26
         128       1.00      0.95      0.98        22
         129       1.00      0.96      0.98        25
         130       0.81      0.87      0.84      1617
         131       0.78      0.68      0.73       481
         132       0.65      0.62      0.64        24
         133       0.95      0.76      0.84        25
         134       0.96      0.92      0.94        24
         135       0.80      1.00      0.89         8
         136       0.89      0.74      0.81        23
         137       0.95      0.95      0.95        22
         138       1.00      1.00      1.00         7
         139       0.96      1.00      0.98        23
         140       1.00      0.69      0.81        16
         141       0.84      0.83      0.84      1441
         142       0.81      0.83      0.82       481
         143       0.92      0.48      0.63        23
         144       0.92      0.96      0.94        24

    accuracy                           0.85     26674
   macro avg       0.91      0.88      0.89     26674
weighted avg       0.85      0.85      0.85     26674

{'Modelo': 'XGBoost', 'Accuracy': 0.8507910324660718, 'Precision': 0.8513767854551417, 'Recall': 0.8507910324660718, 'F1': 0.8503174533352186}

LightGBM

In [20]:
from lightgbm import LGBMClassifier

modelo = LGBMClassifier(
    n_estimators=300,
    max_depth=10,
    learning_rate=0.1,
    num_class=len(np.unique(y_train)),
    objective="multiclass",
    random_state=42,
    verbose=-1
)

resultados.append(
    avaliar(modelo, "LightGBM")
)

Treinando LightGBM...
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.00      0.00      0.00        16
           2       0.00      0.00      0.00      1602
           3       0.00      0.00      0.00       483
           4       0.00      0.00      0.00        24
           5       0.00      0.00      0.00        24
           6       0.00      0.00      0.00        24
           7       0.00      0.00      0.00      1433
           8       0.00      0.00      0.00       472
           9       0.00      0.00      0.00         8
          10       0.00      0.00      0.00         8
          11       0.09      0.02      0.03       644
          12       0.43      0.01      0.02       633
          13       0.00      0.00      0.00        24
          14       0.41      0.08      0.14      1611
          15       0.00      0.00      0.00        37
          16       0.00      0.00      0.00        24
          17       0.00      0.00      0.00        15
          18       0.00      0.00      0.00        16
          19       0.00      0.00      0.00         7
          20       0.00      0.00      0.00        24
          21       0.00      0.00      0.00        23
          22       0.00      0.00      0.00        15
          23       0.00      0.00      0.00        16
          24       0.00      0.00      0.00        23
          25       0.00      0.00      0.00        22
          26       0.00      0.00      0.00        15
          27       0.00      0.00      0.00         8
          28       0.00      0.00      0.00         7
          29       0.00      0.00      0.00        25
          30       0.07      0.82      0.14      1881
          31       0.00      0.00      0.00       477
          32       0.00      0.00      0.00        25
          33       0.00      0.00      0.00        23
          34       0.00      0.00      0.00        25
          35       0.00      0.00      0.00        24
          36       0.00      0.00      0.00        22
          37       0.00      0.00      0.00        25
          38       0.00      0.00      0.00         9
          39       0.00      0.00      0.00        64
          40       0.00      0.00      0.00         8
          41       0.00      0.00      0.00        11
          42       0.00      0.00      0.00        24
          43       0.00      0.00      0.00        25
          44       0.00      0.00      0.00        24
          45       0.00      0.00      0.00        24
          46       0.00      0.00      0.00         8
          47       0.00      0.00      0.00        32
          48       0.00      0.00      0.00        31
          49       0.00      0.00      0.00        66
          50       0.00      0.00      0.00        33
          51       0.00      0.00      0.00        30
          52       0.00      0.00      0.00        32
          53       0.00      0.00      0.00        33
          54       0.00      0.00      0.00        32
          55       0.00      0.00      0.00        24
          56       0.00      0.00      0.00        24
          57       0.00      0.00      0.00        25
          58       0.00      0.00      0.00        26
          59       0.00      0.00      0.00        24
          60       0.00      0.00      0.00        24
          61       0.00      0.00      0.00        25
          62       0.00      0.00      0.00        24
          63       0.00      0.00      0.00        33
          64       0.00      0.00      0.00        31
          65       0.00      0.00      0.00        30
          66       0.00      0.00      0.00        32
          67       0.00      0.00      0.00        32
          68       0.00      0.00      0.00        34
          69       0.00      0.00      0.00        32
          70       0.00      0.00      0.00        34
          71       0.00      0.00      0.00        24
          72       0.00      0.00      0.00        24
          73       0.00      0.00      0.00        33
          74       0.00      0.00      0.00        33
          75       0.00      0.00      0.00        32
          76       0.00      0.00      0.00        32
          77       0.00      0.00      0.00        33
          78       0.00      0.00      0.00        32
          79       0.00      0.00      0.00        31
          80       0.00      0.00      0.00        32
          81       0.00      0.00      0.00        30
          82       0.00      0.00      0.00        31
          83       0.00      0.00      0.00        32
          84       0.00      0.00      0.00        33
          85       0.00      0.00      0.00        33
          86       0.00      0.00      0.00        31
          87       0.00      0.00      0.00        33
          88       0.00      0.00      0.00        29
          89       0.00      0.00      0.00        31
          90       0.44      0.13      0.20       919
          91       0.05      0.06      0.06       965
          92       0.00      0.00      0.00        24
          93       0.00      0.00      0.00        15
          94       0.00      0.00      0.00        23
          95       0.00      0.00      0.00        24
          96       0.00      0.00      0.00        25
          97       0.00      0.00      0.00        46
          98       0.00      0.00      0.00        24
          99       0.00      0.00      0.00        25
         100       0.00      0.00      0.00        16
         101       0.00      0.00      0.00        48
         102       0.00      0.00      0.00        16
         103       0.00      0.00      0.00        25
         104       0.00      0.00      0.00         8
         105       0.06      0.00      0.01      1433
         106       0.00      0.00      0.00       483
         107       0.14      0.00      0.00      1447
         108       0.03      0.02      0.02       482
         109       0.00      0.00      0.00        25
         110       0.00      0.00      0.00        24
         111       0.00      0.00      0.00        24
         112       0.00      0.00      0.00        25
         113       0.00      0.00      0.00        23
         114       0.00      0.00      0.00        24
         115       0.00      0.00      0.00        23
         116       0.00      0.00      0.00      1609
         117       0.04      0.01      0.02       485
         118       0.00      0.00      0.00        24
         119       0.00      0.00      0.00        25
         120       0.00      0.00      0.00        23
         121       0.00      0.00      0.00        24
         122       0.01      0.00      0.00      2082
         123       0.75      0.01      0.01       480
         124       0.00      0.00      0.00        23
         125       0.00      0.00      0.00        24
         126       0.00      0.00      0.00        25
         127       0.00      0.00      0.00        26
         128       0.00      0.00      0.00        22
         129       0.00      0.00      0.00        25
         130       0.09      0.00      0.00      1617
         131       0.00      0.00      0.00       481
         132       0.00      0.00      0.00        24
         133       0.00      0.00      0.00        25
         134       0.00      0.00      0.00        24
         135       0.00      0.00      0.00         8
         136       0.00      0.00      0.00        23
         137       0.00      0.00      0.00        22
         138       0.00      0.00      0.00         7
         139       0.00      0.00      0.00        23
         140       0.00      0.00      0.00        16
         141       0.07      0.00      0.01      1441
         142       0.00      0.00      0.00       481
         143       0.00      0.00      0.00        23
         144       0.00      0.00      0.00        24

    accuracy                           0.07     26674
   macro avg       0.02      0.01      0.00     26674
weighted avg       0.10      0.07      0.03     26674

{'Modelo': 'LightGBM', 'Accuracy': 0.0713803703981405, 'Precision': 0.09530227068575188, 'Recall': 0.0713803703981405, 'F1': 0.02990388799966173}

d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\projetos\Py\Fullstack_ia_python\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

CatBoost

In [21]:
from catboost import CatBoostClassifier

modelo = CatBoostClassifier(
    iterations=300,
    depth=6,
    learning_rate=0.1,
    loss_function="MultiClass",
    random_state=42,
    verbose=100
)

resultados.append(
    avaliar(modelo, "CatBoost")
)

Treinando CatBoost...
0:	learn: 3.7904056	total: 2.62s	remaining: 13m 2s
100:	learn: 1.0326513	total: 3m 43s	remaining: 7m 20s
200:	learn: 0.7759786	total: 7m 24s	remaining: 3m 39s
299:	learn: 0.6543408	total: 11m 9s	remaining: 0us
              precision    recall  f1-score   support

           0       0.78      0.88      0.82         8
           1       1.00      0.94      0.97        16
           2       0.69      0.70      0.70      1602
           3       0.72      0.77      0.74       483
           4       0.88      0.96      0.92        24
           5       1.00      0.92      0.96        24
           6       1.00      0.83      0.91        24
           7       0.87      0.94      0.90      1433
           8       0.79      0.68      0.73       472
           9       1.00      0.75      0.86         8
          10       0.60      0.38      0.46         8
          11       0.67      0.81      0.73       644
          12       0.61      0.69      0.65       633
          13       0.67      0.17      0.27        24
          14       0.80      0.80      0.80      1611
          15       0.68      0.81      0.74        37
          16       0.85      0.71      0.77        24
          17       1.00      0.73      0.85        15
          18       0.93      0.81      0.87        16
          19       0.86      0.86      0.86         7
          20       0.96      1.00      0.98        24
          21       0.72      0.78      0.75        23
          22       0.83      1.00      0.91        15
          23       1.00      0.94      0.97        16
          24       1.00      0.78      0.88        23
          25       0.92      1.00      0.96        22
          26       0.73      0.73      0.73        15
          27       1.00      1.00      1.00         8
          28       1.00      1.00      1.00         7
          29       0.92      0.96      0.94        25
          30       0.75      0.74      0.75      1881
          31       0.72      0.66      0.69       477
          32       0.89      1.00      0.94        25
          33       0.81      0.74      0.77        23
          34       0.71      0.40      0.51        25
          35       0.95      0.88      0.91        24
          36       0.77      0.77      0.77        22
          37       1.00      0.96      0.98        25
          38       0.90      1.00      0.95         9
          39       0.97      1.00      0.98        64
          40       0.67      1.00      0.80         8
          41       1.00      1.00      1.00        11
          42       0.86      0.79      0.83        24
          43       1.00      0.92      0.96        25
          44       0.96      0.96      0.96        24
          45       0.89      1.00      0.94        24
          46       0.89      1.00      0.94         8
          47       0.67      0.50      0.57        32
          48       0.93      0.87      0.90        31
          49       0.79      0.76      0.78        66
          50       0.77      0.82      0.79        33
          51       0.96      0.87      0.91        30
          52       0.93      0.88      0.90        32
          53       0.94      0.94      0.94        33
          54       1.00      1.00      1.00        32
          55       0.86      0.79      0.83        24
          56       0.91      0.88      0.89        24
          57       0.92      0.96      0.94        25
          58       0.76      0.85      0.80        26
          59       0.67      0.67      0.67        24
          60       0.88      0.88      0.88        24
          61       0.82      0.92      0.87        25
          62       0.95      0.88      0.91        24
          63       0.93      0.82      0.87        33
          64       0.60      0.48      0.54        31
          65       0.50      0.60      0.55        30
          66       0.68      0.53      0.60        32
          67       0.86      0.75      0.80        32
          68       0.86      0.88      0.87        34
          69       0.89      0.78      0.83        32
          70       0.89      0.94      0.91        34
          71       0.88      0.96      0.92        24
          72       0.91      0.88      0.89        24
          73       1.00      0.97      0.98        33
          74       1.00      0.97      0.98        33
          75       1.00      1.00      1.00        32
          76       0.97      1.00      0.98        32
          77       0.86      0.91      0.88        33
          78       0.96      0.78      0.86        32
          79       0.78      0.81      0.79        31
          80       0.97      0.94      0.95        32
          81       0.84      0.90      0.87        30
          82       0.97      0.94      0.95        31
          83       0.90      0.88      0.89        32
          84       0.97      0.97      0.97        33
          85       0.84      0.82      0.83        33
          86       0.86      0.97      0.91        31
          87       0.92      1.00      0.96        33
          88       0.75      0.72      0.74        29
          89       0.83      0.77      0.80        31
          90       0.86      0.81      0.83       919
          91       0.64      0.58      0.61       965
          92       0.84      0.88      0.86        24
          93       0.64      0.60      0.62        15
          94       0.85      1.00      0.92        23
          95       0.96      1.00      0.98        24
          96       0.94      0.68      0.79        25
          97       0.85      0.96      0.90        46
          98       0.92      1.00      0.96        24
          99       0.96      0.96      0.96        25
         100       1.00      1.00      1.00        16
         101       0.86      1.00      0.92        48
         102       1.00      0.88      0.93        16
         103       0.88      0.84      0.86        25
         104       1.00      1.00      1.00         8
         105       0.79      0.80      0.79      1433
         106       0.79      0.76      0.78       483
         107       0.71      0.69      0.70      1447
         108       0.79      0.86      0.82       482
         109       0.81      0.88      0.85        25
         110       0.75      0.38      0.50        24
         111       1.00      0.88      0.93        24
         112       1.00      0.96      0.98        25
         113       0.88      1.00      0.94        23
         114       1.00      0.92      0.96        24
         115       0.91      0.91      0.91        23
         116       0.79      0.74      0.77      1609
         117       0.89      0.94      0.92       485
         118       0.88      0.58      0.70        24
         119       1.00      0.56      0.72        25
         120       0.96      1.00      0.98        23
         121       1.00      0.96      0.98        24
         122       0.81      0.84      0.83      2082
         123       0.90      0.91      0.90       480
         124       0.93      0.57      0.70        23
         125       0.62      0.21      0.31        24
         126       0.96      0.92      0.94        25
         127       0.93      1.00      0.96        26
         128       1.00      0.91      0.95        22
         129       0.93      1.00      0.96        25
         130       0.73      0.79      0.76      1617
         131       0.66      0.58      0.62       481
         132       0.55      0.46      0.50        24
         133       0.94      0.60      0.73        25
         134       0.86      1.00      0.92        24
         135       1.00      0.88      0.93         8
         136       1.00      0.74      0.85        23
         137       1.00      0.95      0.98        22
         138       1.00      1.00      1.00         7
         139       0.95      0.91      0.93        23
         140       1.00      0.44      0.61        16
         141       0.76      0.76      0.76      1441
         142       0.76      0.77      0.77       481
         143       1.00      0.35      0.52        23
         144       0.86      1.00      0.92        24

    accuracy                           0.78     26674
   macro avg       0.87      0.83      0.84     26674
weighted avg       0.78      0.78      0.78     26674

{'Modelo': 'CatBoost', 'Accuracy': 0.7768988528154758, 'Precision': 0.7776072400836743, 'Recall': 0.7768988528154758, 'F1': 0.7755329487260636}

### Ranking

In [22]:
ranking = pd.DataFrame(resultados)

ranking.sort_values(
    "F1",
    ascending=False
)

                 Modelo  Accuracy  Precision    Recall        F1
1           Extra Trees  0.852328   0.853604  0.852328  0.851419
3               XGBoost  0.850791   0.851377  0.850791  0.850317
5              CatBoost  0.776899   0.777607  0.776899  0.775533
0         Random Forest  0.635450   0.670736  0.635450  0.629845
2  HistGradientBoosting  0.501087   0.598927  0.501087  0.534876
4              LightGBM  0.071380   0.095302  0.071380  0.029904

### Busca de Hiperparâmetros (RandomizedSearchCV)

O XGBoost teve o melhor resultado no ranking acima, então faço aqui a busca dos melhores hiperparâmetros para ele (essa busca foi movida do `TrainService`, que agora usa os parâmetros já encontrados).

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

parametros = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [4, 6, 8, 10],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0],
} # treina X(100,200,300) modelos na memória, com X(4,6,8,10) de profundidade e X(0.8,1.0) de subsample e colsample_bytree

modelo = XGBClassifier(
    random_state=42,
    eval_metric="mlogloss",
    tree_method="hist"
)

busca = RandomizedSearchCV(
    estimator=modelo,
    param_distributions=parametros,
    n_iter=20,
    cv=5,
    scoring="f1_weighted",
    verbose=1,
    random_state=42,
    n_jobs=-1
)

busca.fit(X_train, y_train)

print("\nMelhores parâmetros:")
print(busca.best_params_)

Os melhores hiperparâmetros foram aplicado no train_service (que no fim não deu uma alteração muito grande de uma aplicação mais simples que eu tinha feito no commit anterior)